In [263]:
import spacy
from spacy.lang.fr.stop_words import STOP_WORDS
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score
import pandas as pd
import re

In [271]:



from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [264]:


# Charger le modèle spaCy pour le français
nlp = spacy.load("fr_core_news_sm")

In [336]:
df = pd.read_csv(r"C:\Users\antoa\Desktop\projet certif\RGBD\table_produits\produits.csv")



In [340]:
df.shape

(1528, 15)

In [338]:
df = df.dropna(subset=['saveur'])

In [339]:
df.saveur.isna().sum()

np.int64(0)

In [341]:
def clean_text_french(text):
    doc = nlp(text)
    # Supprimer les stopwords et les symboles inutiles
    text = ' '.join([token.lemma_ for token in doc if token.text not in STOP_WORDS and token.is_alpha])
    return text.lower()

In [342]:
df['description_cleaned'] = df['description'].apply(clean_text_french)

In [424]:
df['nom_cleaned'] = df['nom_produit'].apply(clean_text_french)

In [274]:
from nltk.corpus import stopwords

https://www.kaggle.com/datasets/heeraldedhia/stop-words-in-28-languages?resource=download&select=french.txt

In [284]:
import os

In [285]:
# Nouveau chemin du fichier french.txt
french_stopwords_path = r'C:\Users\antoa\Desktop\projet certif\app\models\french.txt'

# Vérifier si le fichier existe et le lire
if os.path.exists(french_stopwords_path):
    with open(french_stopwords_path, 'r', encoding='utf-8') as file:
        french_stopwords = file.read().splitlines()  # Lire chaque ligne comme un mot séparé
    print(french_stopwords[:10])  # Afficher les 10 premiers mots vides pour vérifier
else:
    print(f"Le fichier french.txt est introuvable dans {french_stopwords_path}")


['a', 'ai', 'aie', 'aient', 'aies', 'ait', 'alors', 'as', 'au', 'aucun']


In [286]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Utiliser les mots vides français dans le TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words=french_stopwords)
X = vectorizer.fit_transform(df['description_cleaned'])  # Transformer les descriptions en vecteurs
y = df['saveur']  # Cible : saveur

In [287]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score


In [288]:
# Diviser les données en un jeu d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [289]:
# Créer un modèle de régression logistique
model = LogisticRegression(max_iter=1000)

In [290]:
# Entraîner le modèle
model.fit(X_train, y_train)


LogisticRegression(max_iter=1000)

In [291]:
# Prédire les résultats sur le jeu de test
y_pred = model.predict(X_test)

Accuracy: 0.10457516339869281

In [292]:
# Évaluer les performances du modèle
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.10457516339869281
Classification Report:
                                                                                            precision    recall  f1-score   support

                                          amande, cassis, lime, gâteau, cactus, framboise       0.00      0.00      0.00         1
                                                                anis, fruits rouges, lime       0.00      0.00      0.00         1
                                                          anis, tabac, barbe à papa, lime       0.00      0.00      0.00         1
                                                                        anis, tabac, lime       0.34      1.00      0.51        12
                                                                anis, tabac, mangue, lime       0.00      0.00      0.00         1
                                                                anis, tabac, menthe, lime       0.00      0.00      0.00         3
                            

c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [293]:
vectorizer = TfidfVectorizer(
    stop_words=french_stopwords,
    ngram_range=(1, 2),  # Utiliser des bigrammes
    max_df=0.85,  # Ignorer les mots qui apparaissent dans plus de 85% des documents
    min_df=2      # Garder les mots qui apparaissent dans au moins 2 documents
)


In [294]:
X = vectorizer.fit_transform(df['description_cleaned'])  # Transformer les descriptions en vecteurs
y = df['saveur']  # Cible : saveur

In [295]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [296]:
from sklearn.linear_model import LogisticRegression

# Initialiser le modèle de régression logistique
model = LogisticRegression(max_iter=1000)

# Entraîner le modèle avec les données d'entraînement
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [297]:
# Faire des prédictions sur l'ensemble de test
y_pred = model.predict(X_test)


Accuracy: 0.11437908496732026


In [298]:
from sklearn.metrics import classification_report, accuracy_score

# Calculer l'exactitude
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Afficher un rapport détaillé sur les performances
print(classification_report(y_test, y_pred))

Accuracy: 0.11437908496732026
                                                                                           precision    recall  f1-score   support

                                          amande, cassis, lime, gâteau, cactus, framboise       0.00      0.00      0.00         1
                                                                anis, fruits rouges, lime       0.00      0.00      0.00         1
                                                          anis, tabac, barbe à papa, lime       0.00      0.00      0.00         1
                                                                        anis, tabac, lime       0.34      1.00      0.51        12
                                                                anis, tabac, mangue, lime       0.00      0.00      0.00         1
                                                                anis, tabac, menthe, lime       0.00      0.00      0.00         3
                                                  ba

c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anacon

In [299]:
from sklearn.model_selection import GridSearchCV

# Paramètres pour la recherche en grille
param_grid = {
    'C': [0.1, 1, 10],  # Paramètre de régularisation
    'max_iter': [1000, 2000],  # Nombre d'itérations
}

In [300]:
# Initialiser le modèle
model = LogisticRegression()


In [301]:
# Recherche en grille
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, n_jobs=-1)

Meilleurs paramètres: {'C': 10, 'max_iter': 1000}
Accuracy après ajustement des hyperparamètres: 0.19281045751633988

In [302]:
# Entraîner la recherche en grille
grid_search.fit(X_train, y_train)

# Meilleurs paramètres
print("Meilleurs paramètres:", grid_search.best_params_)

# Meilleur modèle
best_model = grid_search.best_estimator_

# Faire des prédictions avec le meilleur modèle
y_pred = best_model.predict(X_test)

# Calculer la précision
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy après ajustement des hyperparamètres:", accuracy)

c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\model_selection\_split.py:776: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


Meilleurs paramètres: {'C': 10, 'max_iter': 1000}
Accuracy après ajustement des hyperparamètres: 0.19281045751633988


In [303]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Exemple d'utilisation d'un modèle différent (Random Forest)
rf_model = RandomForestClassifier()

# Définir une grille d'hyperparamètres
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20],
    'min_samples_split': [2, 5],
}

# Recherche en grille avec validation croisée
grid_search_rf = GridSearchCV(rf_model, param_grid, cv=5, n_jobs=-1)
grid_search_rf.fit(X_train, y_train)

# Meilleurs paramètres
print("Meilleurs paramètres pour Random Forest:", grid_search_rf.best_params_)

# Prédictions avec le meilleur modèle
best_rf_model = grid_search_rf.best_estimator_
y_pred_rf = best_rf_model.predict(X_test)

# Calcul de la précision
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("Accuracy pour Random Forest après ajustement des hyperparamètres:", accuracy_rf)


c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\model_selection\_split.py:776: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


Meilleurs paramètres pour Random Forest: {'max_depth': 20, 'min_samples_split': 5, 'n_estimators': 200}
Accuracy pour Random Forest après ajustement des hyperparamètres: 0.1503267973856209


In [317]:
from sklearn.linear_model import LogisticRegression
from sklearn.multioutput import MultiOutputClassifier
from sklearn.model_selection import train_test_split
import numpy as np
# Données d'exemple : X (features) et y (labels binaires pour chaque saveur)
X = np.random.rand(100, 5)  # 100 exemples, 5 caractéristiques
y = np.random.randint(2, size=(100, 4))  # 100 exemples, 4 saveurs possibles

# Diviser en train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Utiliser MultiOutputClassifier pour traiter chaque label indépendamment
clf = MultiOutputClassifier(LogisticRegression())
clf.fit(X_train, y_train)

# Prédictions
y_pred = clf.predict(X_test)

# Afficher les résultats
print("Prédictions multi-labels:", y_pred)

Prédictions multi-labels: [[0 1 0 1]
 [0 1 0 1]
 [0 1 1 1]
 [0 0 1 0]
 [0 0 1 1]
 [1 1 1 1]
 [1 1 0 1]
 [0 0 1 1]
 [0 0 1 1]
 [0 1 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 1 1 0]
 [1 1 1 1]
 [0 0 1 0]
 [0 0 1 1]
 [1 1 0 1]
 [0 0 1 1]
 [0 1 1 0]
 [1 1 0 0]]


In [318]:
from sklearn.multioutput import ClassifierChain
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Données d'exemple : X (features) et y (labels binaires pour chaque saveur)
X = np.random.rand(100, 5)  # 100 exemples, 5 caractéristiques
y = np.random.randint(2, size=(100, 4))  # 100 exemples, 4 saveurs possibles

# Diviser en train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Utiliser ClassifierChain pour lier les prédictions entre les labels
chain_clf = ClassifierChain(LogisticRegression())
chain_clf.fit(X_train, y_train)

# Prédictions
y_pred = chain_clf.predict(X_test)

# Afficher les résultats
print("Prédictions multi-labels avec Classifier Chain:", y_pred)


Prédictions multi-labels avec Classifier Chain: [[1. 1. 1. 0.]
 [1. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]
 [1. 1. 0. 1.]
 [0. 1. 1. 1.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]
 [1. 1. 0. 0.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [1. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [319]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Données d'exemple : X (features) et y (combinations de saveurs)
X = np.random.rand(100, 5)  # 100 exemples, 5 caractéristiques
y = np.random.randint(2, size=(100, 4))  # 100 exemples, 4 saveurs possibles

# Diviser en train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Utiliser MultiOutputClassifier pour chaque combinaison d'étiquettes
clf = MultiOutputClassifier(LogisticRegression())
clf.fit(X_train, y_train)

# Prédictions
y_pred = clf.predict(X_test)

# Afficher les résultats
print("Prédictions multi-labels avec Label Powerset:", y_pred)

Prédictions multi-labels avec Label Powerset: [[0 1 0 0]
 [0 1 1 1]
 [0 0 0 0]
 [0 0 1 0]
 [0 1 0 1]
 [0 0 0 0]
 [1 1 1 0]
 [0 1 0 1]
 [0 1 0 1]
 [1 1 1 1]
 [1 0 0 0]
 [1 1 1 1]
 [1 1 1 0]
 [0 1 1 0]
 [0 1 0 1]
 [0 1 0 0]
 [0 1 0 0]
 [1 1 1 0]
 [1 0 1 1]
 [1 1 1 1]]


In [ ]:
from sentence_transformers import SentenceTransformer
import numpy as np

# Charger le modèle "all-MiniLM-L6-v2"
model = SentenceTransformer('all-MiniLM-L6-v2')

# Appliquer le modèle aux descriptions de vos produits
descriptions = df['description_cleaned'].tolist()
embeddings = model.encode(descriptions, convert_to_numpy=True)

# Afficher les dimensions des embeddings pour vérifier
print(embeddings.shape)


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Diviser les données en train et test
X_train, X_test, y_train, y_test = train_test_split(embeddings, df['saveur'], test_size=0.2, random_state=42)

# Initialiser et entraîner le classificateur
classifier = LogisticRegression(max_iter=2000)
classifier.fit(X_train, y_train)

# Faire des prédictions sur les données de test
y_pred = classifier.predict(X_test)

# Calculer l'exactitude
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy avec les embeddings : {accuracy}")


si la colonne "saveur" contient des lignes avec plusieurs valeurs séparées par des virgules (comme "fraise, cassis, pastèque"), cela peut poser un problème pour les modèles de classification, car chaque valeur (saveur) devrait être traitée de manière indépendante.

Voici quelques approches pour gérer cette situation :

1. Séparer les valeurs multiples dans "saveur" en plusieurs catégories :
Vous pouvez créer des catégories binaires pour chaque saveur présente dans vos données. Par exemple, si une ligne contient "fraise, cassis, pastèque", vous créez trois colonnes : "fraise", "cassis", et "pastèque", avec des valeurs binaires (1 pour la présence, 0 pour l'absence).

Voici un exemple de ce que vous pouvez faire :

In [304]:
# Séparer les saveurs et les transformer en colonnes binaires
saveurs_split = df['saveur'].str.split(',').apply(lambda x: [s.strip() for s in x])

# Créer un ensemble de toutes les saveurs uniques
all_saveurs = set([item for sublist in saveurs_split for item in sublist])

# Ajouter des colonnes binaires pour chaque saveur
for saveur in all_saveurs:
    df[saveur] = saveurs_split.apply(lambda x: 1 if saveur in x else 0)

# Exemple: vérifier les premières lignes
print(df.head())


                                                 url  \
0  https://www.aromes-et-liquides.fr/e-liquide-ul...   
1  https://www.aromes-et-liquides.fr/e-liquide-ul...   
2  https://www.aromes-et-liquides.fr/e-liquide-al...   
3  https://www.aromes-et-liquides.fr/e-liquide-he...   
4  https://www.aromes-et-liquides.fr/e-liquide-t-...   

                    nom_produit  \
0         Ragnarok Ultimate A&L   
1              Oni Ultimate A&L   
2             A&L Fruits Rouges   
3  Red Light 200ml Hello Cloudy   
4           Red Astaire T-Juice   

                                         img_produit  prix_produit contenance  \
0  https://assets.aromes-et-liquides.fr/53645-thi...          5.90       10ml   
1  https://assets.aromes-et-liquides.fr/53646-thi...          5.90       10ml   
2  https://assets.aromes-et-liquides.fr/53641-thi...          4.90       10ml   
3  https://assets.aromes-et-liquides.fr/45672-thi...         11.34      200ml   
4  https://assets.aromes-et-liquides.fr/55065-t

C:\Users\antoa\AppData\Local\Temp\ipykernel_35964\403493996.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[saveur] = saveurs_split.apply(lambda x: 1 if saveur in x else 0)
C:\Users\antoa\AppData\Local\Temp\ipykernel_35964\403493996.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[saveur] = saveurs_split.apply(lambda x: 1 if saveur in x else 0)
C:\Users\antoa\AppData\Local\Temp\ipykernel_35964\403493996.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` ma

2. Utiliser un modèle multi-label :
Puisque chaque échantillon peut appartenir à plusieurs classes (saveurs), vous pourriez adopter une approche de classification multi-label. Cela permet de prédire plusieurs étiquettes pour chaque échantillon. Dans ce cas, vous pouvez utiliser un modèle comme OneVsRestClassifier pour entraîner un modèle pour chaque saveur.

Voici un exemple pour cela :

In [305]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.linear_model import LogisticRegression

# Transformer la colonne 'saveur' en une matrice de labels binaires
from sklearn.preprocessing import MultiLabelBinarizer


In [314]:
mlb = MultiLabelBinarizer()
y_multi = mlb.fit_transform(df['saveur'].str.split(','))

In [328]:
# Nettoyer les saveurs pour supprimer les symboles non pertinents
df['saveur'] = df['saveur'].apply(lambda x: [s for s in x if isinstance(s, str) and s.isalpha()])


In [329]:
# Étape 1 : Encoder les labels multi-saveurs (multi-label)
mlb = MultiLabelBinarizer()
y = mlb.fit_transform(df['saveur'])

In [330]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Utiliser les mots vides français dans le TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words=french_stopwords)
X = vectorizer.fit_transform(df['description_cleaned'])  # Transformer les descriptions en vecteurs


In [331]:
# Étape 3 : Diviser en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [332]:
# Étape 4 : Entraîner un modèle avec un classificateur multi-output
clf = MultiOutputClassifier(LogisticRegression(max_iter=1000))
clf.fit(X_train, y_train)

MultiOutputClassifier(estimator=LogisticRegression(max_iter=1000))

In [333]:
# Étape 5 : Prédiction
y_pred = clf.predict(X_test)

In [334]:
# Étape 6 : Évaluation du modèle
print("Accuracy score:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred, target_names=mlb.classes_))

Accuracy score: 0.06209150326797386
Classification Report:
               precision    recall  f1-score   support

           a       0.80      1.00      0.89       241
           b       0.97      0.54      0.69       128
           c       0.87      0.86      0.86       175
           d       0.89      0.14      0.24        59
           e       0.99      1.00      1.00       304
           f       0.86      0.47      0.61       116
           g       0.95      0.39      0.55        95
           h       1.00      0.26      0.42        57
           i       1.00      1.00      1.00       306
           j       0.00      0.00      0.00         2
           k       1.00      0.21      0.34        29
           l       0.99      1.00      1.00       304
           m       0.99      1.00      1.00       304
           n       0.73      0.97      0.84       202
           o       0.69      0.93      0.79       167
           p       1.00      0.25      0.40        89
           q       0.

c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [335]:
# Initialiser le modèle SentenceTransformer
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

# Transformer les descriptions en embeddings
embeddings = model.encode(df['description_cleaned'].tolist())

# Convertir les embeddings en un tableau NumPy
embeddings_np = np.array(embeddings)

# Vérifiez les dimensions des embeddings
print("Dimensions des embeddings:", embeddings_np.shape)

Dimensions des embeddings: (1528, 384)


In [343]:
# Créer une liste de toutes les saveurs uniques
all_flavors = set(f for flavors in df['saveur'] for f in flavors)

In [346]:
# Convertir 'all_flavors' en une liste
all_flavors = list(all_flavors)

In [347]:
# Créer une matrice de labels binaires (1 si la saveur est présente, sinon 0)
y = []
for flavors in df['saveur']:
    labels = [1 if flavor in flavors else 0 for flavor in all_flavors]
    y.append(labels)

In [348]:
# Convertir y en un tableau NumPy
y = pd.DataFrame(y, columns=all_flavors)

In [349]:
# Créer une représentation des embeddings de descriptions (exemple avec un tableau fictif)
# Vous devez remplacer ceci par vos propres embeddings générés à partir de 'description_cleaned'
embeddings_np = np.random.rand(len(df), 384)  # Exemple d'embeddings générés (dimension 384)


In [350]:
# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(embeddings_np, y, test_size=0.2, random_state=42)


In [351]:
# Créer et entraîner un modèle de classification multi-label avec Random Forest
model_rf = MultiOutputClassifier(RandomForestClassifier(n_estimators=100))
model_rf.fit(X_train, y_train)

MultiOutputClassifier(estimator=RandomForestClassifier())

In [352]:
# Faire des prédictions
y_pred = model_rf.predict(X_test)


In [356]:
from sklearn.multioutput import MultiOutputClassifier

model_rf = MultiOutputClassifier(RandomForestClassifier(n_estimators=100))
model_rf.fit(X_train, y_train)
y_pred = model_rf.predict(X_test)


In [357]:
# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.0


In [358]:
print("Prédictions:", y_pred)
print("Labels réels:", y_test)


Prédictions: [[0 1 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 1 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]]
Labels réels:       '  m  e  z  h  u  l  n  è  ,  ...  t  s  d  v  y  i  p  w  û  é
439   0  1  1  0  0  0  1  1  0  1  ...  0  0  1  0  0  1  0  0  0  0
76    0  1  1  0  0  0  1  1  0  1  ...  0  0  0  0  0  1  1  0  0  0
1142  0  1  1  0  0  1  1  1  0  1  ...  1  1  1  1  0  1  0  0  0  0
661   0  1  1  0  0  1  1  1  1  1  ...  1  1  1  0  1  1  1  0  0  0
1036  0  1  1  0  0  1  1  1  0  1  ...  1  1  1  1  0  1  0  0  0  0
...  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
1176  0  1  1  0  0  0  1  1  0  1  ...  0  1  0  0  0  1  0  0  0  0
838   0  1  1  0  0  0  1  1  0  1  ...  1  1  0  1  0  1  0  0  0  0
724   0  1  1  0  0  1  1  1  0  1  ...  1  1  0  0  1  1  1  0  0  0
233   0  1  1  0  0  0  1  1  0  1  ...  1  1  0  1  0  1  1  0  0  0
986   0  1  1  0  1  0  1  1  0  1  ...  1  0  0  0  0  1  1  0  0  1

[306 rows x 

In [359]:
# Afficher un rapport de classification
print("Classification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.99      1.00      1.00       304
           2       0.99      1.00      1.00       304
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00        57
           5       0.17      0.03      0.05       113
           6       0.99      1.00      1.00       304
           7       0.66      1.00      0.80       202
           8       0.00      0.00      0.00        25
           9       0.94      1.00      0.97       287
          10       0.00      0.00      0.00         3
          11       0.79      1.00      0.88       241
          12       0.00      0.00      0.00        15
          13       0.66      1.00      0.80       203
          14       0.00      0.00      0.00         2
          15       0.60      0.73      0.66       175
          16       0.67      0.05      0.10       116
    

c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [362]:
df

url  \
0     https://www.aromes-et-liquides.fr/e-liquide-ul...   
1     https://www.aromes-et-liquides.fr/e-liquide-ul...   
2     https://www.aromes-et-liquides.fr/e-liquide-al...   
3     https://www.aromes-et-liquides.fr/e-liquide-he...   
4     https://www.aromes-et-liquides.fr/e-liquide-t-...   
...                                                 ...   
1528  https://www.aromes-et-liquides.fr/e-liquide-al...   
1529  https://www.aromes-et-liquides.fr/e-liquide-81...   
1530  https://www.aromes-et-liquides.fr/e-liquide-th...   
1531  https://www.aromes-et-liquides.fr/e-liquide-be...   
1532  https://www.aromes-et-liquides.fr/e-liquide-al...   

                                            nom_produit  \
0                                 Ragnarok Ultimate A&L   
1                                      Oni Ultimate A&L   
2                                     A&L Fruits Rouges   
3                          Red Light 200ml Hello Cloudy   
4                                   Red Astaire T-Juice   
...                                                 ...   
1528  Blond Mentholé Sel de Nicotine Pur Distillat A...   
1529                                   Nominoë 50ml 814   
1530                 Dervish Fine Cuts Titanide The Fuu   
1531                       Gold Digger Salt Ben Northon   
1532  Blond Sec Sel de Nicotine Pur Distillat Alfali...   

                                            img_produit  prix_produit  \
0     https://assets.aromes-et-liquides.fr/53645-thi...          5.90   
1     https://assets.aromes-et-liquides.fr/53646-thi...          5.90   
2     https://assets.aromes-et-liquides.fr/53641-thi...          4.90   
3     https://assets.aromes-et-liquides.fr/45672-thi...         11.34   
4     https://assets.aromes-et-liquides.fr/55065-thi...          4.90   
...                                                 ...           ...   
1528  https://assets.aromes-et-liquides.fr/55765-thi...          5.90   
1529  https://assets.aromes-et-liquides.fr/56383-thi...         21.90   
1530  https://assets.aromes-et-liquides.fr/55575-thi...          6.90   
1531  https://assets.aromes-et-liquides.fr/56423-thi...          5.90   
1532  https://assets.aromes-et-liquides.fr/55762-thi...          5.90   

                contenance  pg_vg      origine frais surbooste  \
0                     10ml  50/50       France   Oui       Non   
1                     10ml  50/50       France   Oui       Non   
2                     10ml  50/50       France   Non       Non   
3                    200ml  50/50       France   Oui       Oui   
4                     10ml  50/50  Royaume-Uni   Oui       Non   
...                    ...    ...          ...   ...       ...   
1528                  10ml  50/50       France   Non       Non   
1529  50ml (fiole de 60ml)  50/50       France   Non       Oui   
1530                  10ml  50/50       France   Non       Non   
1531                  10ml  50/50       France   Non       Non   
1532                  10ml  50/50       France   Non       Non   

                                                 saveur  \
0                  lime, cassis, fruits rouges, parfait   
1                             citron vert, citron, lime   
2        baies rouges, baie, lime, fruits rouges, baies   
3                       baies, baies rouges, baie, lime   
4     menthol, lime, raisin, menthe, fruits rouges, ...   
...                                                 ...   
1528                          anis, tabac, menthe, lime   
1529                             lime, caramel, biscuit   
1530                                        tabac, anis   
1531                                  anis, tabac, lime   
1532                                  anis, tabac, lime   

                                            description  \
0     Le e-liquide Ragnarok par A&L Ultimate est un ...   
1     Le Oni Ultimate 10ml est un e-liquide pour cig...   
2     Le Fruits Rouges est un e-liquide auxsaveurs d...   
3     Le Red Light,

In [366]:
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report
from transformers import AutoTokenizer, AutoModel
import torch

In [364]:
# Séparer les saveurs dans la colonne 'saveurs' en une liste
all_flavors = set()

# Extraire toutes les saveurs uniques
for flavors in df['saveur']:
    # Séparer les saveurs par virgule et les ajouter au set
    all_flavors.update(flavors.split(', '))

# Convertir en une liste triée si vous le souhaitez
all_flavors = sorted(list(all_flavors))

# Afficher les saveurs uniques
print(all_flavors)

['abricot', 'agrumes', 'amande', 'ananas', 'anis', 'baie', 'baie noire', 'baies', 'baies noires', 'baies rouges', 'banane', 'barbe à papa', 'beignet', 'beurre de cacahuète', 'biscuit', 'bonbon', 'bonbons', 'bubble gum', 'bubblegum', 'cacahuète', 'cactus', 'café', 'cannelle', 'cappuccino', 'caramel', 'caramel beurre salé', 'cassis', 'cerise', 'chantilly', 'cheesecake', 'chocolat', 'citron', 'citron vert', 'clémentine', 'cocktail', 'cola', 'cookie', 'cookie vanillé', 'cookies', 'cornflakes', 'corossol', 'croissant', 'crème anglaise', 'crème brûlée', 'crème pralinée', 'crêpe', 'custard', 'céréale', 'céréales', 'donut', 'eucalyptus', 'figue', 'fondant', 'fraise', 'framboise', 'fruit de la passion', 'fruit du dragon', 'fruit rouge', 'fruit tropical', 'fruits des bois', 'fruits du dragon', 'fruits rouges', 'fruits tropicaux', 'gaufre', 'glace', 'goji', 'grenade', 'grenadine', 'groseille', 'gâteau', 'génoise', 'kiwi', 'kumquat', 'lait', 'lime', 'limonade', 'liqueur', 'litchi', 'macaron', 'mad

In [365]:
# Convertir les saveurs en format binaire (multi-label)
mlb = MultiLabelBinarizer(classes=all_flavors)
y = mlb.fit_transform(df['saveur'].str.split(', '))

In [367]:
# Tokenizer et modèle Hugging Face pour obtenir les embeddings
model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

In [368]:
# Fonction pour obtenir les embeddings
def get_embeddings(texts):
    inputs = tokenizer(texts, padding=True, truncation=True, return_tensors="pt", max_length=512)
    with torch.no_grad():
        outputs = model(**inputs)
    return outputs.last_hidden_state.mean(dim=1).numpy()  # Moyenne des embeddings des tokens

In [370]:
# Vérifier les valeurs nulles ou non valides dans la colonne 'description_cleaned'
print(df['description_cleaned'].isnull().sum())  # Nombre de valeurs nulles
print(df['description_cleaned'].head())  # Aperçu des premières lignes

# Remplacer les valeurs nulles ou non valides par une chaîne vide
df['description_cleaned'] = df['description_cleaned'].fillna('')

0
0    le ragnarok ultimate produitprêt emploipour ci...
1    le oni ultimate cigarette électronique signer ...
2    le fruits rouges auxsaveur baie rougespour cig...
3    le red light unesaveur frais baie rouge recett...
4    le red astaire rencontrer énorme succès arrivé...
Name: description_cleaned, dtype: object


In [375]:
# Charger le tokenizer et le modèle pré-entraîné
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")

# Fonction pour obtenir les embeddings
def get_embeddings(texts):
    # Nettoyer et préparer les données
    texts = [str(text) if isinstance(text, str) else '' for text in texts]
    inputs = tokenizer(texts, padding=True, truncation=True, return_tensors="pt", max_length=512)
    
    # Obtenir les embeddings
    with torch.no_grad():
        outputs = model(**inputs)
        embeddings = outputs.last_hidden_state.mean(dim=1)  # Moyenne des embeddings des tokens

    return embeddings

# Assurez-vous que 'description_cleaned' ne contient pas de valeurs non valides
df['description_cleaned'] = df['description_cleaned'].fillna('')
X = get_embeddings(df['description_cleaned'].values)


KeyboardInterrupt: 

In [ ]:
# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
# Entraîner un modèle de classification multi-label (MLP)
mlp = MLPClassifier(hidden_layer_sizes=(128, 64), max_iter=1000, random_state=42)
mlp.fit(X_train, y_train)

In [ ]:
# Prédictions
y_pred = mlp.predict(X_test)

In [ ]:
# Évaluation du modèle
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")


In [ ]:
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=mlb.classes_))

In [376]:
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [378]:
# Initialisation du modèle SentenceTransformer
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

In [379]:
# Encodage des descriptions des produits en embeddings
descriptions = df['description_cleaned'].tolist()
embeddings_descriptions = model.encode(descriptions, convert_to_tensor=True)

In [380]:
# Encodage des saveurs en embeddings
# Si vous avez plusieurs saveurs, vous pouvez traiter chaque saveur individuellement
saveurs = df['saveur'].apply(lambda x: x.split(', ')).explode().unique().tolist()
embeddings_saveurs = model.encode(saveurs, convert_to_tensor=True)

In [381]:
# Calcul de la similarité cosinus entre les descriptions des produits et les saveurs
cos_sim = cosine_similarity(embeddings_descriptions, embeddings_saveurs)

In [382]:
# Exemple de recommandation pour une saveur donnée
def recommander_produits(saveur):
    # Encode la saveur donnée par l'utilisateur
    saveur_embedding = model.encode([saveur], convert_to_tensor=True)
    
    # Calcule la similarité cosinus entre la saveur demandée et toutes les descriptions
    scores = cosine_similarity(embeddings_descriptions, saveur_embedding)
    
    # Retourne les produits les plus similaires
    top_recommendations = df.iloc[scores.flatten().argsort()[-5:][::-1]]
    return top_recommendations

# Exemple d'utilisation de la fonction de recommandation
recommandations = recommander_produits("fraise")
print(recommandations[['description_cleaned', 'saveur']])

                                    description_cleaned  \
1129  le framboise booster gamme wonderful tart fabr...   
629   le fruit de dragon jaune framboise bleue boost...   
704   le framboise sunset booster format collection ...   
530   un duo bien fruité fois doux parfumer pour rav...   
843   le fraise candy e liquide origine français fab...   

                                                 saveur  
1129              caramel, tarte, lime, café, framboise  
629                             pitaya, framboise, lime  
704                       lime, mûre, framboise, fraise  
530   rose, fruit du dragon, lait, lime, pitaya, fra...  
843                                      bonbon, fraise  


In [383]:
# Encodage des descriptions des produits en embeddings
descriptions = df['description_cleaned'].tolist()
embeddings_descriptions = model.encode(descriptions, convert_to_tensor=True)

In [384]:
# Calcul de la moyenne des embeddings des saveurs pour chaque produit
def get_mean_embedding(saveur_list):
    # On encode chaque saveur et on calcule la moyenne des embeddings
    embeddings = model.encode(saveur_list, convert_to_tensor=True)
    return embeddings.mean(dim=0)

In [385]:
# Application de la fonction pour chaque ligne du dataframe
df['embedding_saveur'] = df['saveur'].apply(lambda x: get_mean_embedding(x.split(', ')))


In [386]:
# Calcul de la similarité cosinus entre les descriptions des produits et les saveurs
# Cosine similarity entre descriptions et saveurs (moyennes des embeddings)
cos_sim = cosine_similarity(embeddings_descriptions, df['embedding_saveur'].tolist())


In [387]:
# Exemple de recommandation pour une saveur donnée
def recommander_produits(saveur):
    # Encode la saveur donnée par l'utilisateur
    saveur_embedding = model.encode([saveur], convert_to_tensor=True)
    
    # Calcule la similarité cosinus entre la saveur demandée et toutes les descriptions
    scores = cosine_similarity(embeddings_descriptions, saveur_embedding)
    
    # Retourne les produits les plus similaires
    top_recommendations = df.iloc[scores.flatten().argsort()[-5:][::-1]]
    return top_recommendations[['description_cleaned', 'saveur']]

In [388]:
# Exemple d'utilisation de la fonction de recommandation
recommandations = recommander_produits("fraise")
print(recommandations)

                                    description_cleaned  \
1129  le framboise booster gamme wonderful tart fabr...   
629   le fruit de dragon jaune framboise bleue boost...   
704   le framboise sunset booster format collection ...   
530   un duo bien fruité fois doux parfumer pour rav...   
843   le fraise candy e liquide origine français fab...   

                                                 saveur  
1129              caramel, tarte, lime, café, framboise  
629                             pitaya, framboise, lime  
704                       lime, mûre, framboise, fraise  
530   rose, fruit du dragon, lait, lime, pitaya, fra...  
843                                      bonbon, fraise  


In [391]:
# Fonction de recommandation
def recommander_produits(saveur):
    saveur_embedding = model.encode([saveur], convert_to_tensor=True)
    scores = cosine_similarity(embeddings_descriptions, saveur_embedding)
    top_recommendations = df.iloc[scores.flatten().argsort()[-5:][::-1]]  # Top 5 recommandations
    
    # Si aucune recommandation n'est trouvée, retourner une valeur par défaut
    if top_recommendations.empty:
        return ['Aucune recommandation']
    
    return top_recommendations['saveur'].values  # Retourne les saveurs recommandées

# Calcul des prédictions pour chaque produit dans le dataframe
df['predictions'] = df['saveur_reelle'].apply(lambda x: recommander_produits(x)[0])  # Prend la 1ère recommandation

# Vérifiez la sortie de la fonction pour vérifier le bon fonctionnement
print(df['predictions'].head())

0       baies rouges, baie, lime, fruits rouges, baies
1             citron vert, citron, fruits rouges, lime
2       baies rouges, baie, lime, fruits rouges, baies
3    mûre, caramel, lime, café, poire, citron vert,...
4                       menthe, menthol, parfait, lime
Name: predictions, dtype: object


In [392]:
df['predictions'] = df['saveur_reelle'].apply(lambda x: recommander_produits(x)[0] if len(recommander_produits(x)) > 0 else 'Aucune recommandation')


In [393]:
from sklearn.metrics import accuracy_score, classification_report

# Calcul de la précision
accuracy = accuracy_score(df['saveur_reelle'], df['predictions'])
print(f"Accuracy: {accuracy * 100:.2f}%")

# Rapport de classification (précision, rappel, F1-score)
report = classification_report(df['saveur_reelle'], df['predictions'])
print("Classification Report:")
print(report)

Accuracy: 2.29%
Classification Report:
                                                                                                                          precision    recall  f1-score   support

                                                                                 agrumes, framboise, fruits rouges, lime       0.00      0.00      0.00         1
                                                                                                           agrumes, lime       0.00      0.00      0.00         2
                                             agrumes, melon, orange, pamplemousse, lime, pastèque, citron, fruits rouges       0.00      0.00      0.00         1
                                                                                                   agrumes, menthe, lime       0.00      0.00      0.00         1
                                                                                   agrumes, menthol, fruits rouges, lime       0.00      0.00      0.0

c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [472]:
df

url  \
0     https://www.aromes-et-liquides.fr/e-liquide-ul...   
1     https://www.aromes-et-liquides.fr/e-liquide-ul...   
2     https://www.aromes-et-liquides.fr/e-liquide-al...   
3     https://www.aromes-et-liquides.fr/e-liquide-he...   
4     https://www.aromes-et-liquides.fr/e-liquide-t-...   
...                                                 ...   
1528  https://www.aromes-et-liquides.fr/e-liquide-al...   
1529  https://www.aromes-et-liquides.fr/e-liquide-81...   
1530  https://www.aromes-et-liquides.fr/e-liquide-th...   
1531  https://www.aromes-et-liquides.fr/e-liquide-be...   
1532  https://www.aromes-et-liquides.fr/e-liquide-al...   

                                            nom_produit  \
0                                 Ragnarok Ultimate A&L   
1                                      Oni Ultimate A&L   
2                                     A&L Fruits Rouges   
3                          Red Light 200ml Hello Cloudy   
4                                   Red Astaire T-Juice   
...                                                 ...   
1528  Blond Mentholé Sel de Nicotine Pur Distillat A...   
1529                                   Nominoë 50ml 814   
1530                 Dervish Fine Cuts Titanide The Fuu   
1531                       Gold Digger Salt Ben Northon   
1532  Blond Sec Sel de Nicotine Pur Distillat Alfali...   

                                            img_produit  prix_produit  \
0     https://assets.aromes-et-liquides.fr/53645-thi...          5.90   
1     https://assets.aromes-et-liquides.fr/53646-thi...          5.90   
2     https://assets.aromes-et-liquides.fr/53641-thi...          4.90   
3     https://assets.aromes-et-liquides.fr/45672-thi...         11.34   
4     https://assets.aromes-et-liquides.fr/55065-thi...          4.90   
...                                                 ...           ...   
1528  https://assets.aromes-et-liquides.fr/55765-thi...          5.90   
1529  https://assets.aromes-et-liquides.fr/56383-thi...         21.90   
1530  https://assets.aromes-et-liquides.fr/55575-thi...          6.90   
1531  https://assets.aromes-et-liquides.fr/56423-thi...          5.90   
1532  https://assets.aromes-et-liquides.fr/55762-thi...          5.90   

                contenance  pg_vg      origine frais surbooste  \
0                     10ml  50/50       France   Oui       Non   
1                     10ml  50/50       France   Oui       Non   
2                     10ml  50/50       France   Non       Non   
3                    200ml  50/50       France   Oui       Oui   
4                     10ml  50/50  Royaume-Uni   Oui       Non   
...                    ...    ...          ...   ...       ...   
1528                  10ml  50/50       France   Non       Non   
1529  50ml (fiole de 60ml)  50/50       France   Non       Oui   
1530                  10ml  50/50       France   Non       Non   
1531                  10ml  50/50       France   Non       Non   
1532                  10ml  50/50       France   Non       Non   

                                                 saveur  ...       gout  \
0                  lime, cassis, fruits rouges, parfait  ...      fruit   
1                             citron vert, citron, lime  ...      fruit   
2        baies rouges, baie, lime, fruits rouges, baies  ...      fruit   
3                       baies, baies rouges, baie, lime  ...      fruit   
4     menthol, lime, raisin, menthe, fruits rouges, ...  ...      fruit   
...                                                 ...  ...        ...   
1528                          anis, tabac, menthe, lime  ...  classique   
1529                             lime, caramel, biscuit  ...  classique   
1530                                        tabac, anis  ...  classique   
1531                                  anis, tabac, lime  ...  classique   
1532                                  anis, tabac, lime  ...  classique   

                                             info_brand id_prod

In [433]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report


# Conversion des embeddings en tableau pour l'apprentissage
X = list(df['embedding_saveur'])
y = df['saveur_reelle']  # Assurez-vous que c'est la colonne correcte

# Séparation du dataset en train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


Accuracy: 49.02%

In [434]:

# Initialisation du classifieur
clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Entraînement du modèle
clf.fit(X_train, y_train)

# Prédictions
predictions = clf.predict(X_test)

# Évaluation du modèle
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Classification Report
print(classification_report(y_test, predictions))


Accuracy: 49.02%
                                                                                                                          precision    recall  f1-score   support

                                                                                                           agrumes, lime       0.00      0.00      0.00         0
                                                                        agrumes, pamplemousse, lime, citron vert, citron       0.00      0.00      0.00         0
                                                                         amande, cassis, lime, gâteau, cactus, framboise       0.00      0.00      0.00         1
                                                                                               anis, fruits rouges, lime       0.00      0.00      0.00         1
                                                                                         anis, tabac, barbe à papa, lime       0.00      0.00      0.00         1
          

c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anacon

amelioration 

xhboost
Accuracy: 58.50%

In [443]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report

In [444]:
vectorizer = TfidfVectorizer(stop_words=french_stopwords)
X = vectorizer.fit_transform(df['description_cleaned'])  # Transformer les descriptions en vecteurs



In [445]:
# Étape 2 : Préparer les cibles (y) - Binariser les étiquettes pour un problème multi-label
mlb = MultiLabelBinarizer()
y = mlb.fit_transform(df['saveur'].apply(lambda x: x.split(', ')))

In [446]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [450]:
# Entraîner un modèle XGBoost pour chaque étiquette
y_pred_all = []
for i in range(y_train.shape[1]):  # Pour chaque label
    # Créer un modèle XGBoost pour chaque étiquette
    dtrain = xgb.DMatrix(X_train, label=y_train[:, i])
    dtest = xgb.DMatrix(X_test)
    
    params = {
        'objective': 'binary:logistic',
        'eval_metric': 'logloss'
    }
    num_round = 100
    bst = xgb.train(params, dtrain, num_round)
    
    # Prédictions pour cette étiquette
    pred = bst.predict(dtest)
    y_pred_all.append(pred)


In [451]:
# Convertir les prédictions en une matrice binaire (0 ou 1)
y_pred = (np.array(y_pred_all) > 0.5).T  # Appliquer un seuil de 0.5


In [452]:
# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 58.50%


In [453]:
# Rapport de classification pour chaque label
print(classification_report(y_test, y_pred, target_names=mlb.classes_))

                     precision    recall  f1-score   support

            abricot       1.00      1.00      1.00         3
            agrumes       1.00      1.00      1.00         1
             amande       1.00      0.75      0.86         4
             ananas       0.90      0.69      0.78        13
               anis       1.00      1.00      1.00        40
               baie       1.00      1.00      1.00        21
         baie noire       0.00      0.00      0.00         0
              baies       1.00      1.00      1.00        21
       baies noires       1.00      1.00      1.00         1
       baies rouges       0.87      0.93      0.90        14
             banane       0.80      1.00      0.89         4
       barbe à papa       1.00      0.90      0.95        10
            beignet       0.00      0.00      0.00         0
beurre de cacahuète       0.00      0.00      0.00         0
            biscuit       1.00      0.90      0.95        10
             bonbon    

c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Un accuracy de 58,50 % signifie que le modèle est capable de prédire correctement environ 58,5 % des instances dans le jeu de test, ce qui est un bon point de départ, mais il y a probablement de la place pour de nombreuses améliorations.

In [467]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

# Initialisation du modèle
xgb_clf = XGBClassifier(n_estimators=100, objective="multi:softmax", num_class=127, random_state=42)

# Entraînement
xgb_clf.fit(X_train, y_train)

# Prédictions
y_pred = xgb_clf.predict(X_test)

# Évaluation
accuracy = accuracy_score(y_test, y_pred)
print(f"XGBoost Multiclass Accuracy: {accuracy * 100:.2f}%")


XGBoostError: [17:46:29] C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0c55ff5f71b100e98-1\xgboost\xgboost-ci-windows\include\xgboost/objective.h:101: multioutput is not supported by the current objective function

In [468]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Initialisation du modèle
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Entraînement
rf_clf.fit(X_train, y_train)

# Prédictions
y_pred = rf_clf.predict(X_test)

# Évaluation
accuracy = accuracy_score(y_test, y_pred)
print(f"Random Forest Multiclass Accuracy: {accuracy * 100:.2f}%")


Random Forest Multiclass Accuracy: 20.59%


# ++++++++++++++++++++++++

1. Stacking (Empilement)
Le stacking combine plusieurs modèles en ajoutant un méta-modèle qui apprend à partir des prédictions des modèles de base. Cela permet de capturer différentes relations dans les données.

# ----------------------------------------

Accuracy: 59.48%

In [441]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MultiLabelBinarizer

# Vectorisation des saveurs (multi-labels)
mlb = MultiLabelBinarizer()
y_train_binary = mlb.fit_transform(y_train.str.split(', '))
y_test_binary = mlb.transform(y_test.str.split(', '))

# Entraîner un modèle de classification multi-labels
clf = MultiOutputClassifier(RandomForestClassifier(n_estimators=100, random_state=42))
clf.fit(X_train, y_train_binary)

# Prédictions
predictions_binary = clf.predict(X_test)

# Calcul de la précision (par exemple, la moyenne des précisions)
accuracy = accuracy_score(y_test_binary, predictions_binary)
print(f"Accuracy: {accuracy * 100:.2f}%")


c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\preprocessing\_label.py:900: UserWarning: unknown class(es) ['kumquat'] will be ignored
  warnings.warn(


Accuracy: 59.48%


# --------------------------

In [ ]:
# Validation croisée
scores = cross_val_score(clf, X, y, cv=5)
print(f"Mean Cross-Validation Score: {scores.mean() * 100:.2f}%")

# Affichage de l'importance des caractéristiques
plt.bar(range(len(clf.feature_importances_)), clf.feature_importances_)
plt.show()

In [407]:
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split


In [408]:
# Séparation des données en features (X) et labels (y)
X = list(df['embedding_saveur'])
y = df['saveur_reelle']  # Assurez-vous que c'est la bonne colonne cible

In [409]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [410]:
# Application de SMOTE pour traiter les classes déséquilibrées
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)


ValueError: Expected n_neighbors <= n_samples_fit, but n_neighbors = 6, n_samples_fit = 1, n_samples = 1

In [411]:
print(y_train.value_counts())


saveur_reelle
lime                                    74
menthe, lime                            18
bonbons, bonbon, lime                   17
anis, tabac, lime                       16
fruits rouges, lime                     15
                                        ..
réglisse, bonbons, bonbon, lime          1
vanille, cookies, cookie, lime, café     1
lime, tabac, cola, chocolat, anis        1
custard, caramel, lime                   1
vanille, amande, lime, biscuit           1
Name: count, Length: 773, dtype: int64


ex

In [412]:
import pandas as pd
from sklearn.metrics import pairwise_distances

# Simulons un DataFrame avec des saveurs réelles (en supposant que vous avez déjà le DataFrame df)
dfs = pd.DataFrame({
    'saveur_reelle': [
        'lime', 'menthe, lime', 'bonbons, bonbon, lime', 'anis, tabac, lime',
        'fruits rouges, lime', 'réglisse, bonbons, bonbon, lime', 'vanille, cookies, cookie, lime, café',
        'lime, tabac, cola, chocolat, anis', 'custard, caramel, lime', 'vanille, amande, lime, biscuit'
    ],
    'produit': ['Produit A', 'Produit B', 'Produit C', 'Produit D', 'Produit E', 'Produit F', 'Produit G', 'Produit H', 'Produit I', 'Produit J']
})

# Transformer les saveurs en ensembles (sets) de saveurs
dfs['saveurs_set'] = dfs['saveur_reelle'].apply(lambda x: set(x.split(', ')))

# Fonction pour obtenir les produits similaires en fonction de la saveur choisie
def recommander_produits(saveur_utilisateur, dfs):
    # Convertir la saveur de l'utilisateur en ensemble
    saveur_utilisateur_set = set(saveur_utilisateur.split(', '))

    # Calculer la similarité entre l'ensemble de saveurs de l'utilisateur et celles des produits
    dfs['similarite'] = dfs['saveurs_set'].apply(lambda x: len(x.intersection(saveur_utilisateur_set)) / len(x))

    # Trier les produits par similarité
    recommandations = dfs.sort_values(by='similarite', ascending=False)
    
    return recommandations[['produit', 'saveur_reelle', 'similarite']]

# Exemple d'utilisation
saveur_utilisateur = 'lime'
recommandations = recommander_produits(saveur_utilisateur, dfs)
print(recommandations)


     produit                         saveur_reelle  similarite
0  Produit A                                  lime    1.000000
1  Produit B                          menthe, lime    0.500000
4  Produit E                   fruits rouges, lime    0.500000
2  Produit C                 bonbons, bonbon, lime    0.333333
3  Produit D                     anis, tabac, lime    0.333333
8  Produit I                custard, caramel, lime    0.333333
5  Produit F       réglisse, bonbons, bonbon, lime    0.250000
9  Produit J        vanille, amande, lime, biscuit    0.250000
7  Produit H     lime, tabac, cola, chocolat, anis    0.200000
6  Produit G  vanille, cookies, cookie, lime, café    0.200000


a nous

In [426]:
df.columns

Index(['url', 'nom_produit', 'img_produit', 'prix_produit', 'contenance',
       'pg_vg', 'origine', 'frais', 'surbooste', 'saveur', 'description',
       'brand', 'gout', 'info_brand', 'id_produit', 'description_cleaned',
       'embedding_saveur', 'saveur_reelle', 'predictions', 'saveur_encoded',
       'nom_cleaned'],
      dtype='object')

In [427]:
# Supposons que vous avez un DataFrame df avec les colonnes 'description_clean' et 'nom_produit'
df['description_nom'] = df['description_cleaned'] + ' ' + df['nom_cleaned']

In [414]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics.pairwise import cosine_similarity

In [428]:
# Utiliser les mots vides français dans le TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words=french_stopwords)
X = vectorizer.fit_transform(df['description_cleaned'])  # Transformer les descriptions en vecteurs
y = df['saveur_reelle']  # Cible : saveur

In [429]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [430]:
# Initialisation du classifieur
clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Entraînement du modèle
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [431]:
# Prédictions sur le jeu de test
y_pred = clf.predict(X_test)

# Évaluation du modèle
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Afficher le rapport de classification
print(classification_report(y_test, y_pred))

Accuracy: 14.05%
                                                                                           precision    recall  f1-score   support

                                          amande, cassis, lime, gâteau, cactus, framboise       0.00      0.00      0.00         1
                                                                anis, fruits rouges, lime       0.00      0.00      0.00         1
                                                          anis, tabac, barbe à papa, lime       0.00      0.00      0.00         1
                                                               anis, tabac, caramel, lime       0.00      0.00      0.00         0
                                                                        anis, tabac, lime       0.50      0.50      0.50        12
                                                                anis, tabac, mangue, lime       0.00      0.00      0.00         1
                                                                a

c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\antoa\anacon